version: "2.3"
services:
  db:
    restart: always
    image: timescale/timescaledb:latest-pg12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: horus1235
      POSTGRES_USER: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"