version: "2.3"
services:
  # db:
  #   restart: always
  #   image: timescale/timescaledb:latest-pg12
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_PASSWORD: horus1235
  #     POSTGRES_USER: postgres
  #   volumes:
  #     - ./db-data:/var/lib/postgresql/data
  #   ports:
  #     - "5433:5432"
  backend:
    build:
        context: .
        dockerfile: ./Dockerfile
    command: bash -c "npm run build && npm run start:temp"
    ports:
        - 3333:3001
        - 3334:3333
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    deploy:
      resources:
          limits:
            cpus: 0.50
            memory: 3000M
